confidence_measure: naive
crop_method: random
crop_size_method: range
dataset:
  json_dir: /root/CS570-Final-Project/datasets/imgnet1k_original/val.json
  num_workers: 0
device: cuda
dropout_rate: 0.05
load_from_checkpoint: false
num_crops: 10
post_proc_logits: majority
relabeled_dataset_save_path: /root/CS570-Final-Project/datasets/imgnet1k_original/random_10_range_naive_majority_0.8.json
threshold: 0.8
