dataset:
  json_dir: /root/CS570-Final-Project/datasets/imgnet1k_original/val.json
  num_workers: 0

load_from_checkpoint: False
device: cuda
relabeled_dataset_save_path: /root/CS570-Final-Project/datasets/imgnet1k_original/val_relabelled_debug.json

crop_method: random
num_crops: 3
crop_size_method: range

confidence_measure: naive
dropout_rate: 0.05
post_proc_logits: average
threshold: 0.6
num_relabel: 100