dataset:
  json_dir: /root/CS570-Final-Project/datasets/imgnet1k_original/val.json
  num_workers: 0

load_from_checkpoint: False
device: cuda
relabeled_dataset_save_path: /root/CS570-Final-Project/datasets/imgnet1k_original/val_relabelled_debug.json

crop_method: random
num_crops: 5
crop_size_method: range

confidence_measure: mc_dropout
dropout_rate: 0.05
post_proc_logits: majority
threshold: 0.5
num_relabel: 1000