dataset:
  json_dir: /root/CS570-Final-Project/datasets/imgnet1k_our/train0.json
  num_workers: 4

load_from_checkpoint: False
device: cuda
relabeled_dataset_save_path: /root/CS570-Final-Project/datasets/imgnet1k_our/train1.json