train_dataset:
  name: train0
  json_dir: /root/CS570-Final-Project/datasets/imgnet1k_our/train0.json
  batch_size: 256
  num_workers: 4

val_datasets:
  - name: ReaL
    json_dir: /root/CS570-Final-Project/datasets/imgnet1k_ReaL/val.json
    batch_size: 512
    num_workers: 4
  - name: orig
    json_dir: /root/CS570-Final-Project/datasets/imgnet1k_original/val.json
    batch_size: 512
    num_workers: 4
  # - name: shankar
  #   json_dir: /root/CS570-Final-Project/datasets/imgnet1k_shankar/val.json
  #   batch_size: 512
  #   num_workers: 4

optimizer:
  lr: 0.001
  weight_decay: 0.0001

num_epochs: 2
load_from_checkpoint: False
start_epoch: 0
scheduler:
  step_size: 30
  gamma: 0.1
device: cuda